image: elixir:latest

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

build:
  stage: build
  script: mix site.build

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
