build:
  stage: build
  image: golang:latest
  script: 
    - make css-ci
    - make run
  artifacts:
    paths:
      - out
deploy:
  stage: deploy
  image: node:lts
  script: npx wrangler pages deploy out --project-name mihaimiuta --branch main
